2017-06-26 03:41:40,934 - reverse.open.20 - ERROR - Exception Logged
Traceback (most recent call last):
  File "reverse.py", line 15, in open
    data = urllib.urlencode(values)
  File "/usr/lib/python2.7/urllib.py", line 1343, in urlencode
    v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)
2017-06-26 03:42:47,522 - reverse.parser.33 - DEBUG - 1
2017-06-26 03:42:47,522 - reverse.parser.33 - DEBUG - nxjyks.cn
2017-06-26 03:42:47,523 - reverse.parser.33 - DEBUG - jiahs@nxu.edu.cn
2017-06-26 03:42:47,523 - reverse.parser.33 - DEBUG - --
2017-06-26 03:42:47,524 - reverse.parser.33 - DEBUG - 北京新网数码信息技术有限公司
2017-06-26 03:42:47,524 - reverse.parser.33 - DEBUG - ns13.xincache.comns14.xincache.com
2017-06-26 03:42:47,525 - reverse.parser.33 - DEBUG - 2012-12-14
2017-06-26 03:42:47,525 - reverse.parser.33 - DEBUG - 2017-12-14
2017-06-26 03:42:47,526 - reverse.parser.33 - DEBUG - 
2017-06-26 03:48:16,632 - reverse.parser.33 - DEBUG - 1
2017-06-26 03:48:16,633 - reverse.parser.33 - DEBUG - nxjyks.cn
2017-06-26 03:48:16,635 - reverse.parser.33 - DEBUG - jiahs@nxu.edu.cn
2017-06-26 03:48:16,635 - reverse.parser.33 - DEBUG - --
2017-06-26 03:48:16,636 - reverse.parser.33 - DEBUG - 北京新网数码信息技术有限公司
2017-06-26 03:48:16,636 - reverse.parser.33 - DEBUG - ns13.xincache.comns14.xincache.com
2017-06-26 03:48:16,636 - reverse.parser.33 - DEBUG - 2012-12-14
2017-06-26 03:48:16,637 - reverse.parser.33 - DEBUG - 2017-12-14
2017-06-26 03:48:16,637 - reverse.parser.33 - DEBUG - 
2017-06-26 03:48:28,378 - reverse.open.20 - ERROR - Exception Logged
Traceback (most recent call last):
  File "reverse.py", line 15, in open
    data = urllib.urlencode(values)
  File "/usr/lib/python2.7/urllib.py", line 1343, in urlencode
    v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)
2017-06-26 03:48:48,893 - reverse.open.20 - ERROR - Exception Logged
Traceback (most recent call last):
  File "reverse.py", line 15, in open
    data = urllib.urlencode(values)
  File "/usr/lib/python2.7/urllib.py", line 1343, in urlencode
    v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)
2017-06-26 03:57:38,793 - getLocal.get_local.22 - DEBUG - 127.0.0.1	IANA保留地址用于本地回送
2017-06-26 03:57:38,840 - getLocal.get_local.22 - DEBUG - 	
2017-06-26 03:58:59,251 - getLocal.get_local.22 - DEBUG - 127.0.0.1	IANA保留地址用于本地回送
2017-06-26 03:58:59,306 - getLocal.get_local.22 - DEBUG - 	
2017-06-26 03:59:53,536 - getLocal.get_local.23 - DEBUG - 127.0.0.1	IANA保留地址用于本地回送
2017-06-26 03:59:53,592 - getLocal.get_local.23 - DEBUG - 	
2017-06-26 04:00:13,119 - getLocal.get_local.23 - DEBUG - 127.0.0.1	
2017-06-26 04:00:13,179 - getLocal.get_local.23 - DEBUG - 	
2017-06-26 04:00:33,098 - getLocal.get_local.23 - DEBUG - 127.0.0.1	
2017-06-26 04:00:33,147 - getLocal.get_local.23 - DEBUG - 	
2017-06-26 04:01:02,033 - getLocal.get_local.23 - DEBUG - 127.0.0.1	
2017-06-26 04:01:02,086 - getLocal.get_local.23 - DEBUG - 	
2017-06-26 04:03:37,833 - getIP.get_ip.32 - DEBUG - 180.149.132.47	baidu.com
2017-06-26 04:04:05,987 - getIP.get_ip.35 - DEBUG - [x]	baidu.com
2017-06-26 04:04:05,987 - getIP.get_ip.36 - DEBUG - [-1, "unsupported operand type(s) for +: 'int' and 'str'"]
2017-06-26 04:04:48,193 - getIP.get_ip.35 - ERROR - [x]	baidu.com
2017-06-26 04:04:48,194 - getIP.get_ip.36 - ERROR - Exception Logged
Traceback (most recent call last):
  File "getIP.py", line 32, in get_ip
    logger.debug(myaddr[0] + '\t' + url)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
2017-06-26 04:05:44,262 - getIP.get_ip.32 - DEBUG - 111.13.101.208	baidu.com
2017-06-26 04:06:00,127 - getIP.get_ip.35 - ERROR - get ip error for baidu.com host
2017-06-26 04:06:00,127 - getIP.get_ip.36 - ERROR - Exception Logged
Traceback (most recent call last):
  File "getIP.py", line 32, in get_ip
    logger.debug(myaddr[0] + '\t' + url)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
2017-06-26 04:07:53,881 - getIP.get_ip.32 - DEBUG - 123.125.114.144	baidu.com
